# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69d9a2a8601b8d0de1ce223fafe5d777e2f587efa0ffc8b33557175dc56d0f67419dea3d8d4b43152d910bbf4ef1e5be415c1ae81b76728c42ae6c0faba85ca0

test:
  secret_key_base: d26569602cd704a25e23c61512da31b696056ef0327ae5d2aa6512315d8c65ab2887ccfd31792b4475876764500e98092d00c8a63bb867f4ac2eb695a2ffdf99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
